### ISSUE TITLE
对这个插件的一点小小的看法

### ISSUE THREAD

**Issue by Well2333** [NumberSir/nonebot-plugin-questionmark#1]
作者应该是刚刚接触的nonebot吧，对于用法不是很熟悉，这很正常。

并不是反对您发表插件，但这个插件安装之后将会阻断一切message类型的事件，导致几乎全部插件均不可用，某种意义上实现了一行代码橄榄你整个bot。

在这里提一个小小的意见，如果您仍然在学习，请 **至少把文档看完** 再来发布插件，否则被不会debug的小白用户安装了，将会导致这种较为隐性的问题，会为社区带来不少的压力。

当然，欢迎您再 **提高代码水平之后** 发布更加有趣的插件！

**Comment by Well2333** [comment]
参考文档

https://v2.nonebot.dev/docs/advanced/matcher#%E9%98%BB%E6%96%AD

NoneBot 内置的事件响应器中，所有非 command 规则的 message 类型的事件响应器都会阻断事件传递，其他则不会。

很显然，on_message在当前版本下会阻断消息的传递，导致其他基于消息事件的插件全部失效。

**Comment by NumberSir** [comment]
> 参考文档
> 
> https://v2.nonebot.dev/docs/advanced/matcher#%E9%98%BB%E6%96%AD
> 
> NoneBot 内置的事件响应器中，所有非 command 规则的 message 类型的事件响应器都会阻断事件传递，其他则不会。
> 
> 很显然，on_message在当前版本下会阻断消息的传递，导致其他基于消息事件的插件全部失效。

什么，原来是这样（
我改用`on_regex`了
