### ISSUE TITLE
提一个关于群聊白名单和出发概率的更新建议

### ISSUE THREAD

**Issue by Poick01** [NumberSir/nonebot-plugin-questionmark#3]
目前插件是只要发的是纯？或！就会回复，但有时候群友想发？表达一些东西的时候bot就会冒出来打断，让群友们会觉得很逆天，所以希望增加一个触发概率的设定，在一定概率内才会触发。如果能在设置一个群聊白名单让指定群聊才可以用这个功能的话，也不怕打扰到比较正式的群了

**Comment by NumberSir** [comment]
> 目前插件是只要发的是纯？或！就会回复，但有时候群友想发？表达一些东西的时候bot就会冒出来打断，让群友们会觉得很逆天，所以希望增加一个触发概率的设定，在一定概率内才会触发。如果能在设置一个群聊白名单让指定群聊才可以用这个功能的话，也不怕打扰到比较正式的群了

已添加，请更新至 v0.4.0

**Comment by Nenot233** [comment]
如果想全部群都想启用，一个群号一个群号填上去好像比较麻烦，有其他的优化办法吗？

**Comment by NumberSir** [comment]
> 如果想全部群都想启用，一个群号一个群号填上去好像比较麻烦，有其他的优化办法吗？

已更新，白名单内填 `"all"` 可启用所有群聊
